# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

project './rx-helper.xcodeproj'

target 'rx-helper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rx-helper
  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  
end
